### ISSUE TITLE
what is z hat Equation (8)

### ISSUE THREAD

**Issue by shalijiang** [Justin1904/Low-rank-Multimodal-Fusion#13]
![image](https://user-images.githubusercontent.com/1907978/93734900-f951bc80-fb8f-11ea-99f8-3f86396d0603.png)

what is \hat{z}_m here? couldn't find its definition. Is it z_m augmented with 1?

**Comment by Justin1904** [comment]
Yep your interpretation is correct. I forgot to introduce \hat{z}_m and I think also might've abused the use of z_m (where it should've been \hat{z}_m) earlier.
