### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by frallisland** [Justin1904/Low-rank-Multimodal-Fusion#16]
The completion epoch is less than I set, and then the following error is generated:
`Traceback (most recent call last):
  File "train_mosi.py", line 246, in <module>
    main(PARAMS)
  File "train_mosi.py", line 226, in main
    min_valid_loss.data.cpu().numpy(), mae, corr, multi_acc, bi_acc, f1])
AttributeError: 'float' object has no attribute 'data'

`

**Comment by Justin1904** [comment]
Not sure what the cause would be. Are you using PyTorch 0.3.1? I got a hunch that maybe the later versions of pytorch could be affecting this. It's been a long time but from what I remember the `min_valid_loss` should've been a tensor, not a Python float.

**Comment by frallisland** [comment]
yes,i using PyTorch 0.3.1.After i track the **min_valid_loss** in the train_mosi.py,the variable is float,because the initialization is **min_valid_loss = float('Inf')**.Maybe i need change type of **min_valid_loss**.

**Comment by Justin1904** [comment]
Good to know! I'll fix this later. Perhaps I should update the whole repo to pytorch 1.5 altogether.
