### ISSUE TITLE
Dimensions of data

### ISSUE THREAD

**Issue by kushagrajain11** [Justin1904/Low-rank-Multimodal-Fusion#3]
Hi
I am not able to understand why the training word vector dimension is (1283, 20, 300)

Each word vector is of size 300, and there are 1283 data points in training data set. But what does 20 represent? Does that mean there is one audio and video feature vector for every 20 words? and one opinion label for every 20 words?

Dimensions of training data points - 
train_audio: (1283, 74)
train_visual: (1283, 46)
train_text: (1283, 20, 300)
train_labels: (1283, 1)

**Comment by Justin1904** [comment]
Each data point originally consists of three sequences:

visual (1, visual_seq_len, 46) --> a sequence of 46 dimensional FACET feature vectors
audio (1, audio_seq_len, 74) --> a sequence of 74 dimensional COVAREP feature vectors
text (1, text_seq_len, 300) --> a sequence of 300 dimensional GloVe word embeddings

here within each data point, visual_seq_len != audio_seq_len != word_seq_len, and they also vary across different data points (e.g audio_seq_len for data point A may be different from that of B). However, we do the following preprocessing to make them into the same shape:

1) for acoustic/visual features, we average across the temporal sequence (xxx_seq_len), hence
(1, visual_seq_len, 46) --> (1, 46)
(1, audio_seq_len, 74) --> (1, 74)

2) for word embeddings, we truncate each sequence to the first 20 words, hence
(1, text_seq_len, 300) --> (1, 20, 300)

through step 1 and 2, we trim all the data points with varying shapes in all three modalities into the same shape, and then we concatenate them together to get

(1283, 46) visual
(1283, 74) audio
(1283, 20, 300) text
