### ISSUE TITLE
about the original face features and audio features

### ISSUE THREAD

**Issue by hugddygff** [Justin1904/Low-rank-Multimodal-Fusion#4]
Hi, Justin,
      Can you share the original face features and audio features with averaging along the temporal dimension?
      and where can I download the original video data of the three datasets?

Thanks very much!

**Comment by Justin1904** [comment]
The link in the README should point to the visual and acoustic features averaged across the temporal dimension. For the original video data, you can download them [here](http://immortal.multicomp.cs.cmu.edu/raw_datasets/). For more info on these datasets, you can check out [CMU-MultimodalSDK](https://github.com/A2Zadeh/CMU-MultimodalSDK).

**Comment by hugddygff** [comment]
sorry, I have made a spelling mistake in the question. I mean the original features without averaging along the temporal dimension.    Instead of with， thanks！

**Comment by Justin1904** [comment]
For that, you could also refer to the Multimodal SDK mentioned above.
