### ISSUE TITLE
Used for classification or to generate a tensor that reduces the amount of calculation？

### ISSUE THREAD

**Issue by Paidalin** [Justin1904/Low-rank-Multimodal-Fusion#7]
My friend uses your code directly as a multimodal decision, but I think your code is just to generate a tensor that reduces the amount of computation, and the output in the code is meant to illustrate that this tensor is valid, not for classification. Is my understanding correct?

**Comment by Justin1904** [comment]
While the proposed method is only for multimodal fusion, the model implemented here is a regression model that *uses* this low-rank fusion method. So the model output will be regression values rather than a representation.

**Comment by Paidalin** [comment]
I want to use your model for classification tasks. If the classification process is using classifier after feature extraction, then your model is like a feature extraction step, right?  The regression value of the output is like the eigenvalue I want.

**Comment by Justin1904** [comment]
Not sure about the eigenvalue argument, but for the first part, yes, our model could act as a feature extraction model that can be trained end-to-end with the classifier itself.

**Comment by Paidalin** [comment]
OK，thank you
